- name: generate /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    unsafe_writes: yes
  register: hosts_updated
- name: Reload facts
  setup:
    gather_subset=network
  when: hosts_updated.changed
