apiVersion: federation/v1beta1
kind: Cluster
metadata:
  name: safespring
spec:
  serverAddressByClientCIDRs:
    - clientCIDR: "0.0.0.0/0"
      serverAddress: "https://193.156.27.71:8443"
  secretRef:
    name: safespring
